### ISSUE TITLE
Automatic notification of failed builds

### ISSUE THREAD

**Issue by jacob-carlborg** [dlang/ci#210] opened 2018-05-18 06:38 UTC
If a build fails, It would be nice if a notification could be sent out to the owner of the project that failed. Perhaps create an issue on that project's GitHub page.

**Comment by wilzbach** [comment] 2018-05-18 07:18
As far as I can tell this is almost impossible to do or at least very tricky with Jenkins.
Martin was recently working on a replacement for this Jenkins project tester, so that might include it or at least make it a lot easier to do.
FWIW though enabling Travis at your project will do almost the same. In this case if I understood correctly the Sociomantic people deliberately merged something that was failing on their Travis and released it.

**Comment by jacob-carlborg** [comment] 2018-05-18 08:09
> As far as I can tell this is almost impossible to do or at least very tricky with Jenkins.

Not sure how this project is setup but wouldn't this [1] take care of it.

>  In this case if I understood correctly the Sociomantic people deliberately merged something that was failing on their Travis and released it.

That's just plain bad.

[1] https://jenkins.io/doc/book/pipeline/syntax/#post

**Comment by wilzbach** [comment] 2018-05-18 09:27
Ah I am terribly sorry for misunderstanding this.

So the failure is related to a new/changed code being added in a new release which now is now failing with DMD?

Not sure whether there's a good way to prevent this a priori except for maybe you using dmd-nightly in your CI too?

**Comment by nemanja-boric-sociomantic** [comment] 2018-05-18 09:36
Ah - the trick is that we're not testing always with the latest version of the compiler. The code works with the dmd v2.078 which is what we're using.

We started working on a new major release to support v2.080: https://github.com/sociomantic-tsunami/ocean/pull/502

**Comment by nemanja-boric-sociomantic** [comment] 2018-05-18 09:41
No, everything is fine, I just wanted to say that we're not _that_ sloppy :-). Even if we would get the CI failures, we would react immediately (and that could be just due to the release process, since we never merge PRs that are failing for whatever reason). I did more investigation and the problem is actually in our code, but it was not visible because of the Travis issue. I'll fix it ASAP: https://github.com/sociomantic-tsunami/ocean/issues/514

**Comment by wilzbach** [comment] 2018-05-18 10:06
Thanks a lot for investigating this and pushing out a PR fix so quickly!
BTW I am not sure on your use cases, but Travis has built-in support for D via the install script

https://dlang.org/install

If you want a global installation, you could just fetch the Debian package from dlang.org?

**Comment by nemanja-boric-sociomantic** [comment] 2018-05-18 10:10
You're welcome! I would ping @leandro-lucarella-sociomantic here to for the install script consideration, thanks for pointing it out!

**Comment by leandro-lucarella-sociomantic** [comment] 2018-05-18 10:56
We just depend on d-apt because, at least in the past, was the best done packaging. We rely a lot on Debian packages to calculate dependendies, so installing packages via `dpkg` instead of `apt` is a real PITA (and back in the days, I don't know how is it now but I would be surprised if it changed, the upstream packages don't split phobos and compiler, so if you have some binary compiled with an "old" phobos with dynamic linking, this approach doesn't work at all.

Packaging is not trivial, specially for a complex environment like Debian, and @jordisayol did a very good job in that sense.

**Comment by leandro-lucarella-sociomantic** [comment] 2018-05-18 10:58
OK, I see you don't even suggest using Debian packages, but downloading an install script. That definitely doesn't suit our needs. If we can't overcome the SF issue, I think we might need to end up creating our own Debian repo somewhere else, which is really a pity and a big duplication of effort.

**Comment by wilzbach** [comment] 2018-07-30 16:44
@jacob-carlborg can we close this as "WONTFIX"?

I don't think we will ever fix the spurious failure problems (we can just try to keep them from appearing all too often) and I assume project owners would still be annoyed be spurious pings.

So far the strategy to ping the project owners if sth. really went constantly red worked quite well.

**Comment by jacob-carlborg** [comment] 2018-07-31 06:10
Feel free to set a label, I don't have that permission.

**Closed** 2018-07-31 06:09 UTC
